### PR TITLE
Fix `cached_block::is_swapped_out()`

### PR DESCRIPTION
**Pull request by MRWITEK**
see `mincore()` [documentation](https://man7.org/linux/man-pages/man2/mincore.2.html).

### CODE REVIEW

**Comment by mhx** [comment]
Hi @MRWITEK, thanks for the PR. The changes for calculating vector size and masking out the LSB make perfect sense. However, this changes the logic of the code. The intent was to check if some data has been *fully* swapped out, but now the code checks if *any pages* have been swapped out.

@miocrime, I wouldn't suspect this PR to cause crashes. Can you reproduce this?

**Comment by mhx** [comment]
I think this makes sense, though. I've just played with it a bit and it makes more sense to evict a block as soon as any parts of it have been swapped out.

**Comment by MRWITEK** [comment]
> The intent was to check if some data has been _fully_ swapped out, but now the code checks if _any pages_ have been swapped out.

For the record, the function named `is_swapped_out` had been returning `true` when any page is reported as resident in memory and `false` when all the pages are swapped out, which seemed like an error by itself; also when `tidy_thread()` uses this function it expects `false` to mean "keep this block". So, I guessed (wrongly) that the intention was to remove from cache the blocks with any number of swapped out pages.

**Comment by mhx** [comment]
The naming of `is_swapped_out` was probably not ideal; the intention was really to return whether *all* pages of the block had been swapped out (which I think it did, albeit probably not in the best way).

Your PR made me think about the behaviour again, and also do some more testing, and I came to the conclusion that it makes more sense to remove blocks from the cache as soon as *any* pages have been swapped out.

I've also now renamed the functions involved to be less ambiguous. `is_swapped_out` is now called `any_pages_swapped_out` and `tidy_collect` has been renamed to `remove_block_if`, making it clear how to interpret the `predicate` argument.

**Pull request merged**
